### ISSUE TITLE
XDV 3.0 - Roadmap to Mainnet

### ISSUE THREAD

**Issue by molekilla** [Electronic-Signatures-Industries/xdv-document-signer#16]
**Pending tasks**

- [ ]  Update migrations to use `USDC` for BSC Mainnet
- [ ]  UI handling, if I connect to wallet , I should enable Sign button, etc.
- [ ] Onboard.js
- [ ]  There will be 4 options only: Offchain, Simple, Protected, Qualified
- [ ]  Create developer docs in `docs.xdv.digital`
- [ ] Complete Signer abstraction in `com.xdv.client.wallet` repo
- [ ]  Fix Share document, Verify document and add a transactions view to display last 20 transactions and link to `bscscan.com` explorer
- [ ]  Link to updated video link
- [ ]  i18n options, Spanish and English
- [ ]  Help icons to explain as much as possible
